import {
  FileArchive,
  FileAudio,
  FileCode,
  FileCode2,
  FileImage,
  FileJson,
  FileSpreadsheet,
  FileTerminal,
  FileText,
  FileVideo
} from 'lucide-react'

/** 后缀 → 图标/颜色（自定风格：lucide + 语言代表色） */
const FILE_ICON_MAP: Record<string, { icon: typeof FileText; cls: string }> = {
  ts: { icon: FileCode2, cls: 'text-[#3178c6]' },
  tsx: { icon: FileCode2, cls: 'text-[#3178c6]' },
  js: { icon: FileCode2, cls: 'text-[#f1e05a]' },
  jsx: { icon: FileCode2, cls: 'text-[#f1e05a]' },
  mjs: { icon: FileCode2, cls: 'text-[#f1e05a]' },
  cjs: { icon: FileCode2, cls: 'text-[#f1e05a]' },
  json: { icon: FileJson, cls: 'text-[#cbcb41]' },
  py: { icon: FileCode, cls: 'text-[#3572a5]' },
  go: { icon: FileCode, cls: 'text-[#00add8]' },
  rs: { icon: FileCode, cls: 'text-[#dea584]' },
  java: { icon: FileCode, cls: 'text-[#b07219]' },
  c: { icon: FileCode, cls: 'text-[#a8b9cc]' },
  h: { icon: FileCode, cls: 'text-[#a8b9cc]' },
  cpp: { icon: FileCode, cls: 'text-[#f34b7d]' },
  hpp: { icon: FileCode, cls: 'text-[#f34b7d]' },
  swift: { icon: FileCode, cls: 'text-[#f05138]' },
  kt: { icon: FileCode, cls: 'text-[#a97bff]' },
  rb: { icon: FileCode, cls: 'text-[#701516]' },
  php: { icon: FileCode, cls: 'text-[#4f5d95]' },
  sh: { icon: FileTerminal, cls: 'text-[#89e051]' },
  bash: { icon: FileTerminal, cls: 'text-[#89e051]' },
  zsh: { icon: FileTerminal, cls: 'text-[#89e051]' },
  html: { icon: FileCode, cls: 'text-[#e34c26]' },
  css: { icon: FileCode, cls: 'text-[#563d7c]' },
  scss: { icon: FileCode, cls: 'text-[#c6538c]' },
  vue: { icon: FileCode, cls: 'text-[#41b883]' },
  svelte: { icon: FileCode, cls: 'text-[#ff3e00]' },
  md: { icon: FileText, cls: 'text-[#519aba]' },
  sql: { icon: FileCode, cls: 'text-[#e38c00]' },
  yaml: { icon: FileText, cls: 'text-[#6d8086]' },
  yml: { icon: FileText, cls: 'text-[#6d8086]' },
  toml: { icon: FileText, cls: 'text-[#6d8086]' },
  ini: { icon: FileText, cls: 'text-[#6d8086]' },
  conf: { icon: FileText, cls: 'text-[#6d8086]' },
  png: { icon: FileImage, cls: 'text-[#a074c4]' },
  jpg: { icon: FileImage, cls: 'text-[#a074c4]' },
  jpeg: { icon: FileImage, cls: 'text-[#a074c4]' },
  gif: { icon: FileImage, cls: 'text-[#a074c4]' },
  svg: { icon: FileImage, cls: 'text-[#a074c4]' },
  webp: { icon: FileImage, cls: 'text-[#a074c4]' },
  ico: { icon: FileImage, cls: 'text-[#a074c4]' },
  zip: { icon: FileArchive, cls: 'text-[#dba34b]' },
  tar: { icon: FileArchive, cls: 'text-[#dba34b]' },
  gz: { icon: FileArchive, cls: 'text-[#dba34b]' },
  tgz: { icon: FileArchive, cls: 'text-[#dba34b]' },
  bz2: { icon: FileArchive, cls: 'text-[#dba34b]' },
  xz: { icon: FileArchive, cls: 'text-[#dba34b]' },
  '7z': { icon: FileArchive, cls: 'text-[#dba34b]' },
  rar: { icon: FileArchive, cls: 'text-[#dba34b]' },
  mp3: { icon: FileAudio, cls: 'text-[#3ba0ad]' },
  wav: { icon: FileAudio, cls: 'text-[#3ba0ad]' },
  flac: { icon: FileAudio, cls: 'text-[#3ba0ad]' },
  ogg: { icon: FileAudio, cls: 'text-[#3ba0ad]' },
  m4a: { icon: FileAudio, cls: 'text-[#3ba0ad]' },
  mp4: { icon: FileVideo, cls: 'text-[#d19a66]' },
  mkv: { icon: FileVideo, cls: 'text-[#d19a66]' },
  mov: { icon: FileVideo, cls: 'text-[#d19a66]' },
  avi: { icon: FileVideo, cls: 'text-[#d19a66]' },
  webm: { icon: FileVideo, cls: 'text-[#d19a66]' },
  pdf: { icon: FileText, cls: 'text-[#e05d5d]' },
  xls: { icon: FileSpreadsheet, cls: 'text-[#217346]' },
  xlsx: { icon: FileSpreadsheet, cls: 'text-[#217346]' },
  csv: { icon: FileSpreadsheet, cls: 'text-[#217346]' },
  doc: { icon: FileText, cls: 'text-[#2b579a]' },
  docx: { icon: FileText, cls: 'text-[#2b579a]' }
}

/** 后缀 → 图标/颜色（自定风格：lucide + 语言代表色）；导出供简介弹窗身份头图复用 */
export function fileVisual(name: string): { icon: typeof FileText; cls: string } {
  const ext = name.includes('.') ? name.split('.').pop()!.toLowerCase() : ''
  return FILE_ICON_MAP[ext] ?? { icon: FileText, cls: 'text-muted' }
}
