import { existsSync, writeFileSync } from 'node:fs'
import { tmpdir } from 'node:os'
import { basename, join, posix } from 'node:path'
import { z } from 'zod'
import { defineTool } from './shared'
import type { SftpEntry } from '../../../shared/types'
import { hostIdSchema, intentSchema, sftpOf, type AnyTool } from './shared'

/** 按路径构造下载用 SftpEntry（download 仅消费 name/path/isDir/size） */
function remoteEntry(path: string, isDir: boolean, size: number): SftpEntry {
  return {
    name: basename(path),
    path,
    isDir,
    isLink: false,
    size,
    permissions: null,
    uid: null,
    gid: null,
    accessed: null,
    modified: null,
    longname: '',
    linkTarget: null
  }
}

/** 传输域：远端下载/上传 + 本机临时文件中转 */
export const transferTools: AnyTool[] = [
  defineTool('sftp_download', {
    description:
      'Download a remote file or directory to the local machine (via SFTP transfer task; progress visible in the UI transfer panel). Auto-detects file vs directory (directories use a single tar stream when tar is available on the remote). Defaults to the system Downloads folder; destDir may specify a local directory (directory only, no filename). Returns the exact local path where it was saved; the download directory is NOT auto-opened.',
    parameters: z.object({
      description: intentSchema,
      hostId: hostIdSchema,
      path: z.string(),
      destDir: z
        .string()
        .optional()
        .describe('Local target directory (absolute path); defaults to the system Downloads folder')
    }),
    handler: async ({ hostId, path, destDir }) => {
      const sftp = await sftpOf(hostId)
      const isDir = await sftp.isDirectory(path)
      const size = isDir ? null : (await sftp.stat(path)).size
      const localPath = await sftp.download(remoteEntry(path, isDir, size ?? 0), destDir, {
        reveal: false
      })
      return { hostId, path, isDir, size, localPath }
    }
  }),

  defineTool('sftp_upload', {
    description:
      'Upload a local file or directory to a remote directory (via SFTP). destDir defaults to remote home. On EPERM/EACCES (macOS folder privacy), do not retry — tell the user to grant Files and Folders access.',
    parameters: z.object({
      description: intentSchema,
      hostId: hostIdSchema,
      localPath: z.string().describe('Absolute path of the local file or directory'),
      destDir: z
        .string()
        .optional()
        .describe('Remote target directory; defaults to the remote home directory')
    }),
    handler: async ({ hostId, localPath, destDir }) => {
      const sftp = await sftpOf(hostId)
      const dest = destDir ?? (await sftp.realpath('.'))
      await sftp.upload([localPath], dest)
      return { hostId, localPath, destPath: posix.join(dest, basename(localPath)), destDir: dest }
    }
  }),

  defineTool('write_temp_file', {
    description:
      'Write text content to a local temp directory and return the full path (useful to stage scripts/configs before sftp_upload or referencing them from execute). On filename conflicts a timestamp prefix is added; existing files are never overwritten.',
    parameters: z.object({
      description: intentSchema,
      content: z.string(),
      name: z
        .string()
        .optional()
        .describe('File name (no directory); a random name is generated by default')
    }),
    handler: async ({ content, name }) => {
      const base = name?.trim()
        ? basename(name.trim())
        : `ggterm-${Date.now()}-${Math.random().toString(36).slice(2, 8)}`
      let filePath = join(tmpdir(), base)
      if (existsSync(filePath)) filePath = join(tmpdir(), `${Date.now()}-${base}`)
      writeFileSync(filePath, content, 'utf8')
      return { path: filePath }
    }
  })
]
